---
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
    version: '>= 1'
  - gem: puppetlabs_spec_helper
    version: '>= 0.8.0'
  - gem: simplecov
Rakefile:
  default_disabled_lint_checks:
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
spec/spec_helper.rb:
  requires: []
