---
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
    version: '>= 1'
  - gem: puppetlabs_spec_helper
    version: '>= 0.8.0'
  - gem: puppet-lint
    version: '>= 1'
  - gem: simplecov
.puppet-lint.rc:
  default_disabled_lint_checks:
  - '80chars'
  - 'class_inherits_from_params_class'
spec/spec_helper.rb:
  requires: []
